# Generated by Django 6.0.3 on 2026-09-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Clube')),
                ('sigla', models.CharField(max_length=5, verbose_name='Sigla')),
                ('fundacao', models.DateField(verbose_name='Data de Fundação')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('estadio', models.CharField(blank=True, max_length=100, verbose_name='Estádio')),
                ('capacidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidade do Estádio')),
                ('divisao', models.CharField(choices=[('serie_a', 'Série A'), ('serie_b', 'Série B'), ('serie_c', 'Série C'), ('serie_d', 'Série D'), ('estadual', 'Estadual'), ('regional', 'Regional'), ('amador', 'Amador')], max_length=20, verbose_name='Divisão')),
                ('cor_primaria', models.CharField(blank=True, max_length=30, verbose_name='Cor Primária')),
                ('cor_secundaria', models.CharField(blank=True, max_length=30, verbose_name='Cor Secundária')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, verbose_name='Site')),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='escudos/', verbose_name='Escudo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clube',
                'verbose_name_plural': 'Clubes',
                'ordering': ['nome'],
            },
        ),
    ]
