# Generated by Django 6.0.3 on 2026-09-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clube',
            name='capacidade',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='telefone',
        ),
    ]
