# Generated by Django 6.0.2 on 2026-09-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clube', '0003_clube_nome_clube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clube',
            name='divisao',
        ),
        migrations.AddField(
            model_name='clube',
            name='cor_terciaria',
            field=models.CharField(blank=True, max_length=30, verbose_name='Cor Terciária'),
        ),
        migrations.AlterField(
            model_name='clube',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome Oficial'),
        ),
    ]
