# Generated by Django 6.1.1 on 2026-09-25 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clube', '0004_remove_clube_divisao_clube_cor_terciaria_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clube',
            table='Clube',
        ),
    ]
