# Generated by Django 6.0.2 on 2026-09-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clube', '0005_alter_clube_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='escudo',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Escudo'),
        ),
    ]
