# Generated by Django 6.1.1 on 2026-09-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clube', '0006_alter_clube_escudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='gestao',
            field=models.CharField(choices=[('ASSOCIATIVO', 'Associativo'), ('SAF', 'SAF'), ('PRIVADO', 'Privado'), ('HIBRIDO', 'Híbrido')], default='ASSOCIATIVO', max_length=20, verbose_name='Modelo de Gestão'),
        ),
    ]
