# Generated by Django 6.0.3 on 2026-09-24 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('codigo_ibge', models.IntegerField(help_text='Código de 2 dígitos do IBGE (ex: 35 para SP, 53 para DF)', primary_key=True, serialize=False)),
                ('uf', models.CharField(help_text='Sigla do estado (ex: SP, RJ)', max_length=2, unique=True, verbose_name='UF')),
                ('nome_estado', models.CharField(max_length=50, verbose_name='Nome do Estado')),
                ('regiao_estado', models.CharField(choices=[('N', 'Norte'), ('NE', 'Nordeste'), ('CO', 'Centro-Oeste'), ('SE', 'Sudeste'), ('S', 'Sul')], max_length=2, verbose_name='Região')),
            ],
            options={
                'verbose_name': 'Estado / UF',
                'verbose_name_plural': 'Estados / UFs',
                'db_table': 'Unidade_Federacao',
                'ordering': ['nome_estado'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('codigo_ibge', models.IntegerField(help_text='Código IBGE de 7 dígitos (ex: 3550308 para São Paulo)', primary_key=True, serialize=False)),
                ('nome_cidade', models.CharField(max_length=100, verbose_name='Nome da Cidade')),
                ('pais', models.CharField(default='Brasil', max_length=50, verbose_name='País')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cidades', to='app_localizacao.estado', verbose_name='Estado / UF')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'Cidade',
                'ordering': ['nome_cidade'],
            },
        ),
    ]
